services:
  - type: web
    name: hostal-django-app
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn Universidad.wsgi:application
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.0